version: '3.4'

services:
  caddy:
    env_file: .env
    image: abiosoft/caddy
    ports:
      - 35370:2015/tcp
    volumes:
      - type: volume
        source: staticfiles
        target: /static
      - type: bind
        source: ./Caddyfile
        target: /etc/Caddyfile
  gpsserver:
    env_file: .env
    environment: 
      - PYTHONUNBUFFERED=1
    image: iavas/gpsserver
    ports:
      - 35370:9000/udp
    volumes:
      - type: volume
        source: staticfiles
        target: /app/static
      - type: volume
        source: gpsdb
        target: /app/db

volumes:
  gpsdb:
  staticfiles:
