# Generated by Django 2.2.6 on 2019-10-15 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataformat', models.IntegerField(choices=[(0, 'Default (0)'), (32, '$GPRMC (32)')], verbose_name='Data format')),
                ('valid', models.BooleanField(verbose_name='Data is valid')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude')),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
                ('speed', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Speed')),
                ('timestamp', models.DateTimeField(verbose_name='GPS Timestamp')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
