# Generated by Django 2.2.6 on 2019-10-15 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpspoints', '0002_auto_20191015_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='geopoint',
            name='course',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='Course'),
        ),
    ]
