# Generated by Django 2.2.6 on 2019-11-18 00:01

from django.db import migrations
from datetime import timedelta

def set_trip(apps, point):
    Trip = apps.get_model("gpspoints", "Trip")
    try:
        trip = Trip.objects.get(
            start__lte = point.timestamp,
            end__gte = point.timestamp - timedelta(minutes=10))

        if trip.end < point.timestamp:
            trip.end = point.timestamp
            trip.save()
    except Trip.DoesNotExist:
        trip = Trip.objects.create(start=point.timestamp, end=point.timestamp)

    point.trip = trip
    point.save()

def update_trips_for_all_points(apps, schema_editor):
    Point = apps.get_model("gpspoints", "GeoPoint")
    points = Point.objects
    total_points = points.count()
    print('There are {} points'.format(points.count()))
    for index, point in enumerate(points.all()):
        set_trip(apps, point)
        if index % 100 == 0:
            print('Completed {0:.2f}%'.format(100.0 * (index+1) / total_points))

class Migration(migrations.Migration):

    dependencies = [
        ('gpspoints', '0004_auto_20191117_2312'),
    ]

    operations = [
        migrations.RunPython(update_trips_for_all_points)
    ]
