# Generated by Django 2.2.6 on 2019-11-18 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpspoints', '0005_set_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopoint',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='gpspoints.Trip'),
        ),
    ]
