# Generated by Django 2.2.6 on 2019-11-18 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpspoints', '0006_auto_20191118_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopoint',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='gpspoints.Trip'),
        ),
    ]
